### ISSUE TITLE
Custom controller - custom model

### ISSUE THREAD

**Issue by kipusoep** [Lecoati/LeBlender#21]
Hi,

Just a question this time.
I'm using a custom controller and I though it would be possible to pass on a custom model to the view, like this:

```
public class TwitterController : LeBlenderController
{
    public ActionResult Index(LeBlenderModel model)
    {
        var item = model.Items.Single();
        string tweetUrl = item.GetValue<string>("tweetURL");
        return View(tweetUrl);
    }
}
```

And the view:

```
@inherits UmbracoViewPage<string>

@Model
```

Unfortunately the Model is null in the view. Am I doing something wrong?

**Comment by sniffdk** [comment]
Try this:

    return View(tweetUrl, item);

**Comment by kipusoep** [comment]
Thanks @sniffdk, your suggestion got me thinking:

```
public class TwitterController : LeBlenderController
{
    public ActionResult Index(LeBlenderModel model)
    {
        var item = model.Items.Single();
        string tweetUrl = item.GetValue<string>("tweetURL");
        return View((object)tweetUrl);
    }
}
```

**Comment by sniffdk** [comment]
Awesome :smiley:

**Comment by tajamal** [comment]
Hi @kipusoep and @sniffdk 

I am looking for a similar solution but i am not hitting Index ActionResult, what do i need to do ?

```
public class ProfileEditLoginController : LeBlenderController
    {
        // GET: ProfileEditLogin
        public ActionResult Index(LeBlenderModel model)
        {

            return View(new ProfileEditLoginView());
        }
}
```

**Comment by tajamal** [comment]
And instead thrown this error message 

`The model item passed into the dictionary is of type 'Lecoati.LeBlender.Extension.Models.LeBlenderModel', but this dictionary requires a model item of type 'MyProject.Models.Profile.ProfileEditLoginView'.`
