### ISSUE TITLE
Problem with reflection in GetLeBlenderControllers

### ISSUE THREAD

**Issue by vnbaaij** [Lecoati/LeBlender#23]
Hi, 

In GetLeBlenderControllers (in Lecoati.LeBlender.Extension.Helper) you scan ALL assemblies for the type LeBlenderController. This crashes however on certain dll's like Microsoft.SingnalR.Core. Because of this a null result is cached  and the scanning will be done again on the next request and so on.

**Comment by soreng** [comment]
@vnbaaij I think this issue has been solved :)
