### ISSUE TITLE
Umbraco 7.4.3: JavaScript crash when creating LeBlender Editor

### ISSUE THREAD

**Issue by LayZeeDK** [Lecoati/LeBlender#32]
I cannot get LeBlender working in Umbraco 7.4.3. I tried installing through the Umbraco Package Repository as well as NuGet.

See attached screenshot for more info.

![image](https://cloud.githubusercontent.com/assets/6364586/15849328/3438a696-2c92-11e6-8a17-ef4ed49eafba.png)

**Comment by LayZeeDK** [comment]
I figured out that I tried creating a new **Data Type** instead of a new **Grid Editor**. I guess this is not a bug then.

**Comment by ryanmcdonough** [comment]
@LayZeeDK can you explain what you mean by this? I'm having the same issue.
