### ISSUE TITLE
Nuget installation - package files not getting copied into project

### ISSUE THREAD

**Issue by ryanology** [Lecoati/LeBlender#39]
I installed version 1.0.8.4 with nuget, and it works fine for me locally, but when anyone else tries to run the project, it doesn't restore all the Leblender files correctly into the project. The correct version of leblender is in my packages.config file, and it seems to copy the dll, but none of the other files (views/js/etc.).

Instead we get the error:

> System.InvalidOperationException: The partial view '/appplugins/leblender/editors/leblendereditor/views/base.cshtml' was not found or no view engine supports the searched locations. The following locations were searched: /appplugins/leblender/editors/leblendereditor/views/base.cshtml

The workaround for us was to just copy all the leblender folders/files from \packages\Lecoati.LeBlender.1.0.8.4\Content\App_Plugins\LeBlender to the App-Plugins\LeBlender folder in the project. When restoring a package, should those folders be getting copied over into the project?

FYI - I am running Umbraco 7.4.3. Thanks.

**Comment by soreng** [comment]
Files are only copied (installed) when the nuget is added. It does not happend when a package is being restored. This is how nuget is designed.

You need to adde the missing files to your VCS :-)

(just like the umbraco files ... )
