### ISSUE TITLE
"Application Name" is shown when using the "Render in the grid" option.

### ISSUE THREAD

**Issue by Zozala** [Lecoati/LeBlender#57]
I'm having an issue when using LeBlender 1.0.8.4 with Umbraco 7.5.4.

![leblender](https://cloud.githubusercontent.com/assets/6716737/20964672/c60e7c74-bc72-11e6-8a57-44e645ca310d.png)

As you can see in the screenshot, there is some weird stuff happening when using the "Render in the grid" option.

Any advice why this is acting like it is and how to fix it?

**Comment by bjarnef** [comment]
Are you sure, you not have included Bootstrap css in the grid editor you render, instead of adding bootstrap css to your template?

**Comment by rhm13** [comment]
I am having the exact same issue over here:

https://our.umbraco.org/forum/using-umbraco-and-getting-started/84780-leblender-injects-bootstrap-styles-into-backoffice

**Comment by rhm13** [comment]
@Zozala, I believe to have solved the issue over on the Our [Umbraco forum](https://our.umbraco.org/forum/using-umbraco-and-getting-started/84780-leblender-injects-bootstrap-styles-into-backoffice)

All the best,
Rhys.

**Comment by soreng** [comment]
Was fixed -- see link above
