### ISSUE TITLE
Solution won't open

### ISSUE THREAD

**Issue by kipusoep** [Lecoati/LeBlender#6]
When I clone the repo to my computer and try to open the solution, I bump into 2 issues:
 1. The project file could not be loaded. Could not find file 'GitHub\LeBlender\Src\Lecoati.LeBlender.Ui\Lecoati.leblender.Ui.csproj'.  
The reason is because it's in the gitignore file.
 2. The references are invalid. Instead of pointing to the NuGet package assemblies, it's referencing "..\..\..\..\Bitbucket\lct_dreampeaks\packages\..."

**Comment by agiraud** [comment]
Oups !! Let me have a look on this

**Comment by kipusoep** [comment]
:+1:

**Comment by agiraud** [comment]
Done !

**Comment by kipusoep** [comment]
Yay, the solution opens and builds :-)
