### ISSUE TITLE
LeBlender creates it's own RTE which is limited to 500 characters

### ISSUE THREAD

**Issue by nul800sebastiaan** [Lecoati/LeBlender#61]
I recently became aware of an issue, which I've described in detail here:
https://our.umbraco.org/documentation/Umbraco-Cloud/Troubleshooting/Plugins-Known-Issues/#leblender

I would recommend to change the `rte`'s `valueType` as a quick fix for future LeBlender installs.

**Comment by soreng** [comment]
@nul800sebastiaan should be fixed in v1.0.9 currently in beta on nuget :)
