### ISSUE TITLE
Render different HTML based on back-office/front-end

### ISSUE THREAD

**Issue by kipusoep** [Lecoati/LeBlender#7]
Hi,

This is more of a feature request than an issue, but would it be possible to detect if the grid editor view is rendered for the back-office or the front-end?
Just like Doc Type Grid Editor:

> If your front end view is rather complex, you may decide that you want to feed the back office
preview an alternative, less complex view. To do this, within your cshtml, simply check for a
querystring parameter dtgePreview being set to “1” to detect being in preview mode to provide an
alternative view.
> Example:
```
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@if(Request.QueryString[“dtgePreview”] == "1"){
// Render preview view
} else {
// Render front end view
}
```

**Comment by agiraud** [comment]
You can try this:

Lecoati.LeBlender.Extension.Helper.IsFrontEnd() 

I have to update the leBlender documentation with that, see more info: https://our.umbraco.org/projects/backoffice-extensions/leblender/general-discussion/64907-How-do-I-see-the-CurrentPage-value

**Comment by kipusoep** [comment]
Great :-) Thanks!
