### ISSUE TITLE
View and config properties is not shown for "custom" datatype

### ISSUE THREAD

**Issue by bjarnef** [Lecoati/LeBlender#72]
I noticed when selecting "custom" datatype option in datatypes dropdown in the property setting dialog, it didn't show the additional "view" and "config" properties.

Furthermore I think it was an issue that this "custom" option just saved an empty string in the guid property, because Angular didn't select the option from the empty value. Instead I have changed this to an empty guid `00000000-0000-0000-0000-000000000000`

![image](https://user-images.githubusercontent.com/2919859/29641921-2f9a7804-8866-11e7-8d94-88f6ded0eb65.png)

**Comment by soreng** [comment]
PR merged :)
